site_name: SRT 项目文档
site_url: https://zengfann.github.io/srt/
edit_uri: ""
repo_url: https://github.com/zengfann/srt
repo_name: zengfann/srt
theme:
  name: material
  language: zh
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
nav:
  - 介绍: index.md
  - 部署:
    - deployment/docker.md
    - deployment/backend.md
    - deployment/frontend.md
    - deployment/nginx.md
  - 数据库设计: database.md
